routes/web.php
<?php
use App\Http\Controllers\DenunciaPersonaDesaparecidaController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SecuestroController;
use App\Http\Controllers\ExtorsionController;
use App\Http\Controllers\LesionesController;
use App\Http\Controllers\VehiculosController;
use App\Http\Controllers\DenunciasController;
use App\Http\Controllers\DelitosSexualesController;
use App\Http\Controllers\RoboTransporteController;
use App\Http\Controllers\RoboCasaController;
use App\Http\Controllers\TrataController;
use App\Http\Controllers\HomicidiosController;
use App\Http\Controllers\FlagranciaController;
use App\Http\Controllers\RoboViolenciaController;
use App\Http\Controllers\TorturaController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\RecursosController;
use App\Http\Controllers\ViolenciaFamiliarController;
use App\Http\Controllers\ExtorsionRedes;
use App\Http\Controllers\LesionGeneroController;
use App\Http\Controllers\SustraccionHijoController;
use App\Http\Controllers\IncumplimientoAlimentariasController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//para ver los estilos
Route::get('/welcome', function () {
    return view('welcome');
});
//rutas del sistema
Route::get('/', function () {
    return view('principal');
})->name('principal');
Route::get('/denuncias_extorsion', function() {
	return view('denuncias_extorsion.principal');
})->name('denuncias_extorsion');
Route::get('extorsion_redes_sociales', [ExtorsionRedes::class, 'alta_extorsion'])->name('extorsion_redes_sociales');


Route::get('telefonica', [ExtorsionController::class, 'tel'])->name('telefonica');
Route::get('correo', [ExtorsionController::class, 'cor'])->name('correo');

Route::get('/finaliza_denuncia', function() {
	return view('listado_denuncias.finish_form');
})->name('finaliza_denuncia');
//rutas lista de denuncias

Route::group(['prefix' => 'lista_denuncias'], function() {
    Route::get('/', function() {
        return view('listado_denuncias.principal');
    })->name('lista_denuncias');

    Route::get('denuncia_tortura', function() {
        return view('listado_denuncias.denuncia_tortura');
    })->name('denuncia_tortura');

    // Route::get('denuncia_flagrancia', function() {
    //     return view('listado_denuncias.denuncia_flagrancia');
    // })->name('denuncia_flagrancia');

    // Route::get('denuncia_pdesaparecida', function() {
    //     return view('listado_denuncias.denuncia_pdesaparecida');
    // })->name('denuncia_pdesaparecida');

    Route::get('denuncia_secuestro', function() {
        return view('listado_denuncias.denuncia_secuestro');
    })->name('denuncia_secuestro');

    Route::get('denuncia_rtransporte', function() {
        return view('listado_denuncias.denuncia_rtransporte');
    })->name('denuncia_rtransporte');
    //Denuncia por robo de casa habitación
    Route::get('denuncia_rviolencia', function() {
        return view('listado_denuncias.denuncia_rviolencia');
    })->name('denuncia_rviolencia');

    Route::get('denuncia_dsexuales', function() {
        return view('listado_denuncias.denuncia_dsexuales');
    })->name('denuncia_dsexuales');


    Route::get('denuncia_otras', function() {
        return view('listado_denuncias.denuncia_otras');
    })->name('denuncia_otras');
});

Route::group(['prefix' => 'denuncias_robo'], function() {
    Route::get('/', function() {
        return view('denuncias_robos.principal');
    })->name('robo');
});

Route::group(['prefix' => 'denuncias_genero'], function() {
    Route::get('/', function() {
        return view('denuncias_genero.principal');
    })->name('genero');
});

Route::resource('secuestro', SecuestroController::class);
Route::get('denuncia_secuestro', [SecuestroController::class, 'alta_secuestro'])->name('denuncia_secuestro');

Route::resource('rtransporte', RoboTransporteController::class);
Route::get('denuncia_rtransporte', [RoboTransporteController::class, 'alta_rtransporte'])->name('denuncia_rtransporte');

Route::resource('pdesaparecida', DenunciaPersonaDesaparecidaController::class);
Route::get('denuncia_pdesaparecida', [DenunciaPersonaDesaparecidaController::class, 'create'])->name('denuncia_pdesaparecida');
Route::resource('delitos_sexuales', DelitosSexualesController::class);
Route::get('denuncia_dsexuales', [DelitosSexualesController::class, 'alta_dsexual'])->name('denuncia_dsexuales');
Route::resource('delitos_rviolencia', RoboViolenciaController::class);
Route::get('denuncia_rviolencia', [RoboViolenciaController::class, 'alta_rviolencia'])->name('denuncia_rviolencia');
Route::resource('delito_tortura', TorturaController::class);
Route::get('denuncia_tortura', [TorturaController::class, 'alta_dtortura'])->name('denuncia_tortura');

Route::post('combo_municipios',[DenunciasController::class, 'combo_municipios'])->name('combo_municipios');
//no la encuentra en el servidor online
Route::get('combo_coloniasGet',[DenunciasController::class, 'combo_colonias'])->name('combo_coloniasGet');

///rutas de lesiones
Route::resource('lesiones', LesionesController::class);
// Route::get('lesiones', [LesionesController::class, 'create'])->name('lesiones');
// Route::post('lesiones_store', [LesionesController::class, 'lesiones_store'])->name('lesiones_store');
//rutas de vehículos
Route::resource('vehiculos', VehiculosController::class);
Route::post('combo_submarca',[VehiculosController::class, 'combo_submarca'])->name('combo_submarca');
//rutas de trata
Route::resource('trata', TrataController::class);
//rutas de denuncia homicidio
Route::resource('homicidios', HomicidiosController::class);

//Rutas para la extorsion
Route::get('denuncias_extorsion', [ExtorsionController::class, 'alta_extorsion'])->name('denuncias_extorsion');
Route::get('combo',[ExtorsionController::class, 'combo'])->name('combo');
Route::post('guarda_extorsion', [ExtorsionController::class, 'guarda_extorsion'])->name('guarda_extorsion');

//rutas de Robo de casa
Route::get('denuncia_rcasa',[RoboCasaController::class,'alta_robo_casa'])->name('denuncia_rcasa');
Route::post('guarda_rcasa', [RoboCasaController::class, 'guarda_rcasa'])->name('guarda_rcasa');
// rutas de Robo en flagrancia
Route::resource('flagrancia', FlagranciaController::class);

///rutas de ViolenciaFamiliar
Route::resource('violencia_familiar', ViolenciaFamiliarController::class);
Route::get('violencia_familiar',[ViolenciaFamiliarController::class,'create'])->name('violencia_familiar');

///rutas de Lesiones de Genero
Route::resource('lesion_genero', LesionGeneroController::class);
Route::get('lesion_genero', [LesionGeneroController::class, 'lesiones'])->name('lesion_genero');

///rutas de Sustraccion de Hijo 
Route::resource('sustraccion_hijo', SustraccionHijoController::class);
Route::get('sustraccion_hijo', [SustraccionHijoController::class, 'sustraccion'])->name('sustraccion_hijo');

///rutas de Incumplimiento de Obligaciones Alimentarias
Route::resource('incum_alimen', IncumplimientoAlimentariasController::class);
Route::get('incum_alimen', [IncumplimientoAlimentariasController::class, 'incum'])->name('incum_alimen');


// rutas de login
Route::get('login', [LoginController::class,'login'])->name('login');
Route::post('validar', [LoginController::class,'validar'])->name('validar');
Route::get('inicio', [LoginController::class,'inicio'])->name('inicio');
//consultas de denuncias
Route::get('consulta_denuncias', [DenunciasController::class, 'index'])->name('consulta_denuncias');
Route::get('json_denuncias', [DenunciasController::class, 'json_denuncias'])->name('json_denuncias');
Route::get('pdf_denuncias/{id}', [DenunciasController::class, 'pdf_denuncias'])->name('pdf_denuncias');
/// get codigo postal
Route::post('codigo_postal',[RecursosController::class, 'codigo_postal'])->name('codigo_postal');
Route::post('combo_loc',[DenunciasController::class, 'combo_loc'])->name('combo_loc');

resources/views/denuncia_vehiculos/combo_submarca.blade.php
@foreach($submarcas as $modelo)
<option value = '{{$modelo->id_submarca}}' id="modelo_vehiculo_denunciante">{{$modelo->submarca}}</option>
@endforeach

resources/views/denuncia_vehiculos/form_vehiculos.blade.php
@extends('listado_denuncias.forms')
@section('titulo')
DENUNCIA DE ROBO DE VEHÍCULOS
@endsection
@section('campos')
    @section('inicio_form')
        <form id="form_advanced_validation" name="form" method="POST" action="{{route('vehiculos.store')}}" enctype="multipart/form-data">
            @csrf
    @endsection
    @section('campos_intermedios')
        <div class="secciones_den"><h3>Datos del Vehículo</h3></div>
        <div class="separacion_den"></div>
        <div class="row clearfix">
            <div class="col-sm-12">
                <div class="form-group form-float">
                    <div class="form-line">
                        <p class="card-inside-title">¿Cuenta con seguro contra robo? *</p>
                        <input type="radio" name="seguro" id="seguro_si" class="with-gap radio-col-brown"  {{old('seguro') == '1' ? 'checked' : ''}} value="1" required>
                        <label for="seguro_si">Sí</label>
                        <input type="radio" name="seguro" id="seguro_no" class="with-gap radio-col-brown"  {{old('seguro') == '0' ? 'checked' : ''}} value="0" required>
                        <label for="seguro_no">No</label>
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group form-float">
                    <label class="form-label">Marca Vehículo *</label>
                    <div class="form-line">
                        <select class="form-control show-tick" name="marca_vehiculo_denunciante" id="marca_vehiculo_denunciante" required>
                            <option value="">Seleccione</option>
                            @forelse($marcas_vehiculo as $marca)
                            <option value="{{$marca->id_marca}}" {{old('marca_vehiculo_denunciante') == $marca->id_marca ? "selected" : ""}}>{{$marca->marca}}</option>
                            @empty
                                Sin marcas de vehiculos
                            @endforelse
                        </select>
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group form-float">
                    <label class="form-label">Modelo Vehículo *</label>
                    <div class="form-line">
                        <select class="form-control show-tick" {{ old('modelo_vehiculo_denunciante') }} name="modelo_vehiculo_denunciante" id="modelo_vehiculo_denunciante" required></select>
                        <input type="hidden" name="modelo_vehiculo_nombre" id="modelo_vehiculo_nombre" value="{{ old('modelo_vehiculo_nombre') }}">
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group form-float">
                    <label class="form-label">Tipo Vehículo *</label>
                    <div class="form-line">
                        <select class="form-control show-tick" name="tipo_vehiculo_denunciante" id="tipo_vehiculo_denunciante" required>
                            <option value="">Seleccione</option>
                            @forelse($t_vehiculos as $t_vehiculo)
                            <option value="{{$t_vehiculo->id_tvehiculos}}" {{old('tipo_vehiculo_denunciante') == $t_vehiculo->id_tvehiculos ? "selected" : ""}}>{{$t_vehiculo->tipo_vehiculos}}</option>
                            @empty
                                Sin tipos de vehículo
                            @endforelse
                        </select>
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group form-float">
                    <label class="form-label">Color Vehículo *</label>
                    <div class="form-line">
                        <select class="form-control show-tick" name="color_vehiculo_denunciante" id="color_vehiculo_denunciante" required>
                            <option value="">Seleccione</option>
                            @forelse($color_vehiculo as $color)
                            <option value="{{$color->id_color}}" {{old('color_vehiculo_denunciante') == $color->id_color ? "selected" : ""}}>{{$color->color}}</option>
                            @empty
                                Sin tipos de vehículo
                            @endforelse
                        </select>
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group form-float">
                    <label class="form-label">Aseguradora</label>
                    <div class="form-line">
                        <select class="form-control show-tick" name="aseguradora_vehiculo" id="aseguradora_vehiculo" required>
                            <option value="">Seleccione</option>
                            @forelse($aseguradoras as $aseguradora)
                            <option value="{{$aseguradora->id_aseguradora}}" {{old('aseguradora_vehiculo') == $aseguradora->id_aseguradora ? "selected" : ""}}>{{$aseguradora->aseguradora}}</option>
                            @empty
                                Sin aseguradoras en DB
                            @endforelse
                        </select>
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group form-float">
                    <label class="form-label">Tipo de placa *</label>
                    <div class="form-line">
                        <select class="form-control show-tick" name="tipo_placa" id="tipo_placa">
                            <option value="">Seleccione</option>
                            <option value="0" {{ old('tipo_placa') == 0 ? 'selected' : ''}} >Servicio Particular</option>
                            <option value="1" {{ old('tipo_placa') == 1 ? 'selected' : ''}} >Servicio Público Estatal</option>
                            <option value="2" {{ old('tipo_placa') == 2 ? 'selected' : ''}} >Servicio Público Federal</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="form-group form-float">
                    <div class="form-line">
                        <input type="text" class="form-control" name="placas_vehiculo_denunciante" id="placas_vehiculo_denunciante" value="{{ old('placas_vehiculo_denunciante') }}" required>
                        <label class="form-label">Placas *</label>
                    </div>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="form-group form-float">
                    <div class="form-line">
                        <input type="text" class="form-control" name="numero_serie" id="numero_serie" value="{{ old('numero_serie') }}" required>
                        <label class="form-label">Número de serie *</label>
                    </div>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="form-group form-float">
                    <div class="form-line">
                        <input type="text" class="form-control" name="num_motor" id="num_motor" value="{{ old('num_motor') }}" required>
                        <label class="form-label">No. Motor *</label>
                    </div>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="form-group form-float">
                    <div class="form-line">
                        <input type="text" class="form-control" name="num_serie_vehiculo_denunciante" id="num_serie_vehiculo_denunciante" value="{{ old('num_serie_vehiculo_denunciante') }}" required>
                        <label class="form-label">No. Serie Vehículo *</label>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-12">
        </div>
            <div class="secciones_den"><h3>Robo de Objetos</h3></div>
            <div class="separacion_den"></div>
            <br>
            <br>
            <div class="form-group form-float">
                <div class="form-line">
                    <textarea class="form-control " name="robo_objetos" id="robo_objetos" style="height: 200px" maxlength="4000" required>{{ old('robo_objetos') }}</textarea>
                    <label class="form-label">Robo de Objetos</label>
                </div>
            </div>
            <br>
    @endsection
    @section('fin_form')
        </form>

<script type="text/javascript" nonce="{{ csp_nonce() }}">
    $(document).ready(function(){
            // var modelo_vehiculo = $("#modelo_vehiculo_denunciante option:selected").text();
            // console.log(modelo_vehiculo);
            // if(modelo_vehiculo !== null){
            //     $("#modelo_vehiculo_nombre").val(modelo_vehiculo);
            // }
            $("#modelo_vehiculo_denunciante").change(function() {
                var modelo_vehiculo = $("#modelo_vehiculo_denunciante option:selected").text();
                $("#modelo_vehiculo_nombre").val(modelo_vehiculo);
            });
        });
    </script>
<!--Combos para codigo postal-->
<script src="{{asset('js/valForms.js')}}" nonce="{{ csp_nonce() }}"></script>
<!--Combos para vehiculos -->
<script type="text/javascript" nonce="{{ csp_nonce() }}">
    let url = "{{route('combo_submarca')}}";
  </script>
<script src="{{asset('js/combos_vehiculos.js')}}" nonce="{{ csp_nonce() }}"></script>

<!--Fin combos para vehiculos -->
    @endsection
@endsection