routes/web.php
<?php
use App\Http\Controllers\DenunciaPersonaDesaparecidaController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SecuestroController;
use App\Http\Controllers\ExtorsionController;
use App\Http\Controllers\LesionesController;
use App\Http\Controllers\VehiculosController;
use App\Http\Controllers\DenunciasController;
use App\Http\Controllers\DelitosSexualesController;
use App\Http\Controllers\RoboTransporteController;
use App\Http\Controllers\RoboCasaController;
use App\Http\Controllers\TrataController;
use App\Http\Controllers\HomicidiosController;
use App\Http\Controllers\FlagranciaController;
use App\Http\Controllers\RoboViolenciaController;
use App\Http\Controllers\TorturaController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\RecursosController;
use App\Http\Controllers\ViolenciaFamiliarController;
use App\Http\Controllers\ExtorsionRedes;
use App\Http\Controllers\LesionGeneroController;
use App\Http\Controllers\SustraccionHijoController;
use App\Http\Controllers\IncumplimientoAlimentariasController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//para ver los estilos
Route::get('/welcome', function () {
    return view('welcome');
});
//rutas del sistema
Route::get('/', function () {
    return view('principal');
})->name('principal');
Route::get('/denuncias_extorsion', function() {
	return view('denuncias_extorsion.principal');
})->name('denuncias_extorsion');
Route::get('extorsion_redes_sociales', [ExtorsionRedes::class, 'alta_extorsion'])->name('extorsion_redes_sociales');


Route::get('telefonica', [ExtorsionController::class, 'tel'])->name('telefonica');
Route::get('correo', [ExtorsionController::class, 'cor'])->name('correo');

Route::get('/finaliza_denuncia', function() {
	return view('listado_denuncias.finish_form');
})->name('finaliza_denuncia');
//rutas lista de denuncias

Route::group(['prefix' => 'lista_denuncias'], function() {
    Route::get('/', function() {
        return view('listado_denuncias.principal');
    })->name('lista_denuncias');

    Route::get('denuncia_tortura', function() {
        return view('listado_denuncias.denuncia_tortura');
    })->name('denuncia_tortura');

    // Route::get('denuncia_flagrancia', function() {
    //     return view('listado_denuncias.denuncia_flagrancia');
    // })->name('denuncia_flagrancia');

    // Route::get('denuncia_pdesaparecida', function() {
    //     return view('listado_denuncias.denuncia_pdesaparecida');
    // })->name('denuncia_pdesaparecida');

    Route::get('denuncia_secuestro', function() {
        return view('listado_denuncias.denuncia_secuestro');
    })->name('denuncia_secuestro');

    Route::get('denuncia_rtransporte', function() {
        return view('listado_denuncias.denuncia_rtransporte');
    })->name('denuncia_rtransporte');
    //Denuncia por robo de casa habitación
    Route::get('denuncia_rviolencia', function() {
        return view('listado_denuncias.denuncia_rviolencia');
    })->name('denuncia_rviolencia');

    Route::get('denuncia_dsexuales', function() {
        return view('listado_denuncias.denuncia_dsexuales');
    })->name('denuncia_dsexuales');


    Route::get('denuncia_otras', function() {
        return view('listado_denuncias.denuncia_otras');
    })->name('denuncia_otras');
});

Route::group(['prefix' => 'denuncias_robo'], function() {
    Route::get('/', function() {
        return view('denuncias_robos.principal');
    })->name('robo');
});

Route::group(['prefix' => 'denuncias_genero'], function() {
    Route::get('/', function() {
        return view('denuncias_genero.principal');
    })->name('genero');
});

Route::resource('secuestro', SecuestroController::class);
Route::get('denuncia_secuestro', [SecuestroController::class, 'alta_secuestro'])->name('denuncia_secuestro');

Route::resource('rtransporte', RoboTransporteController::class);
Route::get('denuncia_rtransporte', [RoboTransporteController::class, 'alta_rtransporte'])->name('denuncia_rtransporte');

Route::resource('pdesaparecida', DenunciaPersonaDesaparecidaController::class);
Route::get('denuncia_pdesaparecida', [DenunciaPersonaDesaparecidaController::class, 'create'])->name('denuncia_pdesaparecida');
Route::resource('delitos_sexuales', DelitosSexualesController::class);
Route::get('denuncia_dsexuales', [DelitosSexualesController::class, 'alta_dsexual'])->name('denuncia_dsexuales');
Route::resource('delitos_rviolencia', RoboViolenciaController::class);
Route::get('denuncia_rviolencia', [RoboViolenciaController::class, 'alta_rviolencia'])->name('denuncia_rviolencia');
Route::resource('delito_tortura', TorturaController::class);
Route::get('denuncia_tortura', [TorturaController::class, 'alta_dtortura'])->name('denuncia_tortura');

Route::post('combo_municipios',[DenunciasController::class, 'combo_municipios'])->name('combo_municipios');
//no la encuentra en el servidor online
Route::get('combo_coloniasGet',[DenunciasController::class, 'combo_colonias'])->name('combo_coloniasGet');

///rutas de lesiones
Route::resource('lesiones', LesionesController::class);
// Route::get('lesiones', [LesionesController::class, 'create'])->name('lesiones');
// Route::post('lesiones_store', [LesionesController::class, 'lesiones_store'])->name('lesiones_store');
//rutas de vehículos
Route::resource('vehiculos', VehiculosController::class);
Route::post('combo_submarca',[VehiculosController::class, 'combo_submarca'])->name('combo_submarca');
//rutas de trata
Route::resource('trata', TrataController::class);
//rutas de denuncia homicidio
Route::resource('homicidios', HomicidiosController::class);

//Rutas para la extorsion
Route::get('denuncias_extorsion', [ExtorsionController::class, 'alta_extorsion'])->name('denuncias_extorsion');
Route::get('combo',[ExtorsionController::class, 'combo'])->name('combo');
Route::post('guarda_extorsion', [ExtorsionController::class, 'guarda_extorsion'])->name('guarda_extorsion');

//rutas de Robo de casa
Route::get('denuncia_rcasa',[RoboCasaController::class,'alta_robo_casa'])->name('denuncia_rcasa');
Route::post('guarda_rcasa', [RoboCasaController::class, 'guarda_rcasa'])->name('guarda_rcasa');
// rutas de Robo en flagrancia
Route::resource('flagrancia', FlagranciaController::class);

///rutas de ViolenciaFamiliar
Route::resource('violencia_familiar', ViolenciaFamiliarController::class);
Route::get('violencia_familiar',[ViolenciaFamiliarController::class,'create'])->name('violencia_familiar');

///rutas de Lesiones de Genero
Route::resource('lesion_genero', LesionGeneroController::class);
Route::get('lesion_genero', [LesionGeneroController::class, 'lesiones'])->name('lesion_genero');

///rutas de Sustraccion de Hijo 
Route::resource('sustraccion_hijo', SustraccionHijoController::class);
Route::get('sustraccion_hijo', [SustraccionHijoController::class, 'sustraccion'])->name('sustraccion_hijo');

///rutas de Incumplimiento de Obligaciones Alimentarias
Route::resource('incum_alimen', IncumplimientoAlimentariasController::class);
Route::get('incum_alimen', [IncumplimientoAlimentariasController::class, 'incum'])->name('incum_alimen');


// rutas de login
Route::get('login', [LoginController::class,'login'])->name('login');
Route::post('validar', [LoginController::class,'validar'])->name('validar');
Route::get('inicio', [LoginController::class,'inicio'])->name('inicio');
//consultas de denuncias
Route::get('consulta_denuncias', [DenunciasController::class, 'index'])->name('consulta_denuncias');
Route::get('json_denuncias', [DenunciasController::class, 'json_denuncias'])->name('json_denuncias');
Route::get('pdf_denuncias/{id}', [DenunciasController::class, 'pdf_denuncias'])->name('pdf_denuncias');
/// get codigo postal
Route::post('codigo_postal',[RecursosController::class, 'codigo_postal'])->name('codigo_postal');
Route::post('combo_loc',[DenunciasController::class, 'combo_loc'])->name('combo_loc');

resources/views/layouts/app-admin.blade.php
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport"
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>FGJEM | Pre-denuncia Web</title>
    <!-- Favicon-->
    <link rel="icon" href="{{asset('images/logo_fgjem.png')}}" type="image/x-icon">
    <script src="{{asset('jquery/jquery-3.3.1.min.js')}}" nonce="{{ csp_nonce() }}"></script>

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" nonce="{

    <link href="https://fonts.googleapis.com/css2?family=Material+Icons" rel="stylesheet" nonce="{{ csp_no
    <!-- Bootstrap Core Css -->
    <link href="{{asset('plugins/bootstrap/css/bootstrap.css')}}" nonce="{{ csp_nonce() }}" rel="styleshee

    <!-- Waves Effect Css -->
    <link href="{{asset('plugins/node-waves/waves.css')}}" rel="stylesheet" nonce="{{ csp_nonce() }}"  />

    <!-- Animation Css -->
    <link href="{{asset('plugins/animate-css/animate.css')}}" rel="stylesheet" nonce="{{ csp_nonce() }}"  

    <!-- Light Gallery Plugin Css -->
    <link href="{{asset('plugins/light-gallery/css/lightgallery.css')}}" rel="stylesheet" nonce="{{ csp_no

    <!-- Custom Css -->
    <link href="{{asset('css/style.css')}}" nonce="{{ csp_nonce() }}" rel="stylesheet">

    <!-- AdminBSB Themes. You can choose a theme from css/themes instead of get all themes -->
    <link href="{{asset('css/themes/all-themes.css')}}" rel="stylesheet" nonce="{{ csp_nonce() }}"  />
    <!-- Bootstrap Select Css -->
    <link href="{{asset('plugins/bootstrap-select/css/bootstrap-select.css')}}" nonce="{{ csp_nonce() }}" 

    <!-- Dropzone Css-->
    <link href="{{asset('dropzone/dropzone.css')}}" rel="stylesheet" nonce="{{ csp_nonce() }}" >


    <STYLE nonce="{{ csp_nonce() }}">
        A {
            text-decoration: none;
        }

    </STYLE>


</head>

<body class="theme-red">
    <!-- Page Loader -->
    <div class="page-loader-wrapper">
        <div class="loader">
            <div class="preloader">
                <div class="spinner-layer pl-red">
                    <div class="circle-clipper left">
                        <div class="circle"></div>
                    </div>
                    <div class="circle-clipper right">
                        <div class="circle"></div>
                    </div>
                </div>
            </div>
            <p>Por favor espere</p>
        </div>
    </div>
    <!-- #END# Page Loader -->
    <!-- Overlay For Sidebars -->
    <div class="overlay"></div>
    <!-- #END# Overlay For Sidebars -->
    <!-- Search Bar -->

    <!-- #END# Search Bar -->
    <!-- Top Bar -->
    <nav class="navbar">
        <div class="container-fluid">
            <div class="navbar-header">
                <a href="javascript:void(0);" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#navbar-collapse" aria-expanded="false"></a>
                <a href="javascript:void(0);" class="bars"></a>
                <a class="navbar-brand" href="{{route('principal')}}">Pre-denuncia Web</a>
            </div>
        </div>
    </nav>
    <!-- #Top Bar -->
    <section>
        <!-- Left Sidebar -->
        <aside id="leftsidebar" class="sidebar">
            <!-- User Info -->
            <div class="user-info">
                <div class="image">
                    <img src="{{asset('images/logo_fgjem.png')}}" width="135" height="130" alt="User" />
                </div>
            </div>
            <!-- #User Info -->
            <!-- Menu -->
            <div class="menu">
                {{-- <ul class="list">
                    <li class="header">MENU DE NAVEGACIÓN</li>
                    <li class="active">
                        <a href="{{route('principal')}}">
                            <i class="material-icons">home</i>
                            <span>Inicio</span>
                        </a>
                    </li>
                    <li>
                        <a href="{{@route('denuncias_extorsion')}}">
                            <i class="material-icons">view_list</i>
                            <span>Extorsiones</span>
                        </a>
                    </li>
                    <a href="javascript:void(0);" class="menu-toggle">
                        <i class="material-icons">view_list</i>
                        <span>Robos</span>
                    </a>
                    <ul class="ml-menu">
                        {{-- <li>
                            <a href="{{route('vehiculos.index')}}">Robo de vehiculos</a>
                        </li>
                        <li>
                            <a href="{{route('denuncia_rcasa')}}">Robo a casa hab.</a>
                        </li>
                        <li>
                            <a href="{{route('flagrancia.create')}}">Robo en flagrancia</a>
                        </li>
                        <li>
                            <a href="{{route('denuncia_rviolencia')}}">Robo con violencia</a>
                        </li>
                        <li>
                            <a href="{{route('denuncia_rtransporte')}}">Transporte público</a>
                        </li> --}}
                    {{-- </ul>

                    <a href="javascript:void(0);" class="menu-toggle">
                        <i class="material-icons">view_list</i>
                        <span>Género</span>
                    </a>
                    <ul class="ml-menu"> --}}
                        {{-- <li>
                            <a href="{{route('denuncia_dsexuales')}}">Delitos Sexuales</a>
                        </li>
                        <li>
                            <a href="">Incumplimiento de Oblicaciones Alimentarias</a>
                        </li>
                        <li>
                            <a href="">Sustracción de Hijo</a>
                        </li>
                        <li>
                            <a href="">Lesiones en Razón de Genero </a>
                        </li>
                        <li>
                            <a href="">Otros</a>
                        </li> --}}
                    {{-- </ul>

                    <a href="javascript:void(0);" class="menu-toggle">
                        <i class="material-icons">view_list</i>
                        <span>Denuncias</span>
                    </a>
                    <ul class ="ml-menu"> --}}
                        {{-- <li>
                        <a href="{{route('denuncia_pdesaparecida')}}">Persona desaparecida</a>
                        </li>
                        <li>
                            <a href="{{route('denuncia_secuestro')}}">Secuestro</a>
                        </li>
                        <li>
                            <a href="{{route('homicidios.index')}}">Homicidio</a>
                        </li>
                        <li>
                            <a href="{{route('denuncia_tortura')}}">Tortura</a>
                        </li>
                        <li>
                            <a href="{{route('trata.index')}}">Trata de personas</a>
                        </li> --}}

                    {{-- </ul>

                </ul> --}} 
            </div>
            <!-- #Menu -->
            <!-- Footer -->

            <!-- #Footer -->
        </aside>
        <!-- #END# Left Sidebar -->
        <!-- Right Sidebar -->

        <!-- #END# Right Sidebar -->
        <!-- CONTENIDO :D -->
    </section>

    <section class="content">
        <div class="container-fluid">
            @include('/layouts/flash-message')
            @yield('content')
            @yield('scripts')
            @yield('script')
        </div>
    </section>
    </div>

    <!-- Jquery Core Js -->
    <script  src="{{asset('plugins/jquery/jquery.min.js')}}" nonce="{{ csp_nonce() }}"></script>

    <!-- Bootstrap Core Js -->
    <script nonce="{{ csp_nonce() }}" src="{{asset('plugins/bootstrap/js/bootstrap.js')}}"></script>

    <!-- Select Plugin Js -->


    <!-- Slimscroll Plugin Js -->
    <script nonce="{{ csp_nonce() }}" src="{{asset('plugins/jquery-slimscroll/jquery.slimscroll.js')}}"></

    <!-- Jquery Validation Plugin Css -->
    <script  src="{{asset('plugins/jquery-validation/jquery.validate.js')}}" nonce="{{ csp_nonce() }}"></s

    <!-- JQuery Steps Plugin Js -->
    <script nonce="{{ csp_nonce() }}" src="{{asset('plugins/jquery-steps/jquery.steps.js')}}"></script>

    <!-- Sweet Alert Plugin Js -->
    <script  nonce="{{ csp_nonce() }}" src="{{asset('plugins/sweetalert/sweetalert.min.js')}}"></script>

    <!-- Waves Effect Plugin Js -->
    <script src="{{asset('plugins/node-waves/waves.js')}}" nonce="{{ csp_nonce() }}" ></script>

    <!-- Custom Js -->
    <script src="{{asset('js/admin.js')}}" nonce="{{ csp_nonce() }}" ></script>
    <script nonce="{{ csp_nonce() }}" src="{{asset('js/pages/forms/form-validation.js')}}"></script>

    <!-- Demo Js -->
    <script src="{{asset('js/demo.js')}}" nonce="{{ csp_nonce() }}" ></script>

    <script nonce="{{ csp_nonce() }}" src="{{asset('js/pages/forms/advanced-form-elements.js')}}"></script

    <!-- Dropzone Js-->
    <script src="{{asset('dropzone/dropzone.js')}}" nonce="{{ csp_nonce() }}" ></script>
</body>

</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>FGJEM | Pre-denuncia Web</title>
    <!-- Favicon-->
    <link rel="icon" href="{{asset('images/logo_fgjem.png')}}" type="image/x-icon">
    <script src="{{asset('jquery/jquery-3.3.1.min.js')}}" nonce="{{ csp_nonce() }}"></script>

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" nonce="{{ csp_nonce() }}" rel="stylesheet" type="text/css">

    <link href="https://fonts.googleapis.com/css2?family=Material+Icons" rel="stylesheet" nonce="{{ csp_nonce() }}" >
    <!-- Bootstrap Core Css -->
    <link href="{{asset('plugins/bootstrap/css/bootstrap.css')}}" nonce="{{ csp_nonce() }}" rel="stylesheet">

    <!-- Waves Effect Css -->
    <link href="{{asset('plugins/node-waves/waves.css')}}" rel="stylesheet" nonce="{{ csp_nonce() }}"  />

    <!-- Animation Css -->
    <link href="{{asset('plugins/animate-css/animate.css')}}" rel="stylesheet" nonce="{{ csp_nonce() }}"  />

    <!-- Light Gallery Plugin Css -->
    <link href="{{asset('plugins/light-gallery/css/lightgallery.css')}}" rel="stylesheet" nonce="{{ csp_nonce() }}" >

    <!-- Custom Css -->
    <link href="{{asset('css/style.css')}}" nonce="{{ csp_nonce() }}" rel="stylesheet">

    <!-- AdminBSB Themes. You can choose a theme from css/themes instead of get all themes -->
    <link href="{{asset('css/themes/all-themes.css')}}" rel="stylesheet" nonce="{{ csp_nonce() }}"  />
    <!-- Bootstrap Select Css -->
    <link href="{{asset('plugins/bootstrap-select/css/bootstrap-select.css')}}" nonce="{{ csp_nonce() }}" rel="stylesheet" />

    <!-- Dropzone Css-->
    <link href="{{asset('dropzone/dropzone.css')}}" rel="stylesheet" nonce="{{ csp_nonce() }}" >
    
    <link href="{{asset('plugins/sweetalert/sweetalert.css')}}" rel="stylesheet"  nonce="{{ csp_nonce() }}"/>

    <meta http-equiv="Content-Security-Policy-Report-Only: policy ">

    <STYLE nonce="{{ csp_nonce() }}">
        A {
            text-decoration: none;
        }

    </STYLE>


</head>

<body class="theme-red">
    <!-- Page Loader -->
    <div class="page-loader-wrapper">
        <div class="loader">
            <div class="preloader">
                <div class="spinner-layer pl-red">
                    <div class="circle-clipper left">
                        <div class="circle"></div>
                    </div>
                    <div class="circle-clipper right">
                        <div class="circle"></div>
                    </div>
                </div>
            </div>
            <p>Por favor espere</p>
        </div>
    </div>
    <!-- #END# Page Loader -->
    <!-- Overlay For Sidebars -->
    <div class="overlay"></div>
    <!-- #END# Overlay For Sidebars -->
    <!-- Search Bar -->

    <!-- #END# Search Bar -->
    <!-- Top Bar -->
    <nav class="navbar">
        <div class="container-fluid">
            <div class="navbar-header">
                <a href="javascript:void(0);" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#navbar-collapse" aria-expanded="false"></a>
                <a href="javascript:void(0);" class="bars"></a>
                <a class="navbar-brand" href="{{route('principal')}}">Pre-denuncia Web</a>
            </div>
        </div>
    </nav>
    <!-- #Top Bar -->
    <section>
        <!-- Left Sidebar -->
        <aside id="leftsidebar" class="sidebar">
            <!-- User Info -->
            <div class="user-info">
                <div class="image">
                    <img src="{{asset('images/logo_fgjem.png')}}" width="135" height="130" alt="User" />
                </div>
            </div>
            <!-- #User Info -->
            <!-- Menu -->
            <div class="menu">
                <ul class="list">
                    <li class="header">MENU DE NAVEGACIÓN</li>
                    <li class="active">
                        <a href="{{route('principal')}}">
                            <i class="material-icons">home</i>
                            <span>Inicio</span>
                        </a>
                    </li>
                    <li>
                        <a href="javascript:void(0);" class="menu-toggle">
                            <i class="material-icons">view_list</i>
                            <span>Extorsiones</span>
                        </a>
                        <ul class="ml-menu">
                        <li>
                            <a href="{{route('denuncias_extorsion')}}">Presencial</a>
                        </li>
                        <li>
                            <a href="{{route('telefonica')}}">Telefónica</a>
                        </li>
                        <li>
                            <a href="{{route('correo')}}">Correo</a>
                        </li>
                        <li>
                            <a href="{{route('extorsion_redes_sociales')}}">Redes Sociales</a>
                        </li>
                    </ul>
                    </li>
                    <a href="javascript:void(0);" class="menu-toggle">
                        <i class="material-icons">view_list</i>
                        <span>Robos</span>
                    </a>
                    <ul class="ml-menu">
                        <li>
                            <a href="{{route('vehiculos.index')}}">Robo de vehiculos</a>
                        </li>
                        <li>
                            <a href="{{route('denuncia_rcasa')}}">Robo a casa hab.</a>
                        </li>
                        <li>
                            <a href="{{route('flagrancia.create')}}">Robo en flagrancia</a>
                        </li>
                        <li>
                            <a href="{{route('denuncia_rviolencia')}}">Robo con violencia</a>
                        </li>
                        <li>
                            <a href="{{route('denuncia_rtransporte')}}">Transporte público</a>
                        </li>
                    </ul>

                    <a href="javascript:void(0);" class="menu-toggle">
                        <i class="material-icons">view_list</i>
                        <span>Género</span>
                    </a>
                    <ul class="ml-menu">
                        <li>
                            <a href="{{route('denuncia_dsexuales')}}">Delitos Sexuales</a>
                        </li>
                        <li>
                            <a href="{{route('incum_alimen')}}">Incumplimiento de Obligaciones Alimentarias</a>
                        </li>
                        <li>
                            <a href="{{route('violencia_familiar')}}">Violencia Familiar</a>
                        </li>
                        <li>
                            <a href="{{route('sustraccion_hijo')}}">Sustracción de Hijo</a>
                        </li>
                        <li>
                            <a href="{{route('lesion_genero')}}">Lesiones en Razón de Genero </a>
                        </li>
                        <li>
                            <a href="{{route('lista_denuncias')}}">Otros</a>
                        </li>
                    </ul>

                    <a href="javascript:void(0);" class="menu-toggle">
                        <i class="material-icons">view_list</i>
                        <span>Denuncias</span>
                    </a>
                    <ul class ="ml-menu">
                        <li>
                        <a href="{{route('denuncia_pdesaparecida')}}">Persona desaparecida</a>
                        </li>
                        <li>
                            <a href="{{route('denuncia_secuestro')}}">Secuestro</a>
                        </li>
                        <li>
                            <a href="{{route('homicidios.index')}}">Homicidio</a>
                        </li>
                        <li>
                            <a href="{{route('denuncia_tortura')}}">Tortura</a>
                        </li>
                        <li>
                            <a href="{{route('trata.index')}}">Trata de personas</a>
                        </li>
                    </ul>

                </ul>
            </div>
            <!-- #Menu -->
            <!-- Footer -->

            <!-- #Footer -->
        </aside>
        <!-- #END# Left Sidebar -->
        <!-- Right Sidebar -->

        <!-- #END# Right Sidebar -->
        <!-- CONTENIDO :D -->
    </section>

    <section class="content">
        <div class="container-fluid">
            <!--@include('/layouts/flash-message')-->
            @yield('content')
            @yield('scripts')
            @yield('script')
        </div>
    </section>
    </div>

    <!-- Jquery Core Js -->
    <script  src="{{asset('plugins/jquery/jquery.min.js')}}" nonce="{{ csp_nonce() }}"></script>

    <!-- Bootstrap Core Js -->
    <script nonce="{{ csp_nonce() }}" src="{{asset('plugins/bootstrap/js/bootstrap.js')}}"></script>

    <!-- Select Plugin Js -->


    <!-- Slimscroll Plugin Js -->
    <script nonce="{{ csp_nonce() }}" src="{{asset('plugins/jquery-slimscroll/jquery.slimscroll.js')}}"></script>

    <!-- Jquery Validation Plugin Css -->
    <script  src="{{asset('plugins/jquery-validation/jquery.validate.js')}}" nonce="{{ csp_nonce() }}"></script>

    <!-- JQuery Steps Plugin Js -->
    <script nonce="{{ csp_nonce() }}" src="{{asset('plugins/jquery-steps/jquery.steps.js')}}"></script>

    <!-- Sweet Alert Plugin Js -->
    <script   src="{{asset('plugins/sweetalert/sweetalert.min.js')}}" nonce="{{ csp_nonce() }}"></script>
    @include('sweetalert::alert')
    <!-- Waves Effect Plugin Js -->
    <script src="{{asset('plugins/node-waves/waves.js')}}" nonce="{{ csp_nonce() }}" ></script>

    <!-- Custom Js -->
    <script src="{{asset('js/admin.js')}}" nonce="{{ csp_nonce() }}" ></script>
    <script nonce="{{ csp_nonce() }}" src="{{asset('js/pages/forms/form-validation.js')}}"></script>

    <!-- Demo Js -->
    {{-- <script src="{{asset('js/demo.js')}}" nonce="{{ csp_nonce() }}" ></script> --}}

    <script nonce="{{ csp_nonce() }}" src="{{asset('js/pages/forms/advanced-form-elements.js')}}"></script>

    <!-- Dropzone Js-->
    <script src="{{asset('dropzone/dropzone.js')}}" nonce="{{ csp_nonce() }}" ></script>
</body>

</html>

resources/views/layouts/flash-message.blade.php
@if ($message = Session::get('success'))
<div class="alert alert-success alert-block">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <strong>{{ $message }}</strong>
</div>
@endif

@if ($message = Session::get('error'))
<div class="alert alert-danger alert-block">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <strong>{{ $message }}</strong>
</div>
@endif

@if ($message = Session::get('warning'))
<div class="alert alert-warning alert-block">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <strong>{{ $message }}</strong>
</div>
@endif

@if ($message = Session::get('info'))
<div class="alert alert-info alert-block">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <strong>{{ $message }}</strong>
</div>
@endif

@if ($errors->any())
<div class="alert alert-danger">
    <button type="button" class="close" data-dismiss="alert">×</button>
    Por favor, revise los errores encontrados.
</div>
@endif